# dependencies: 
#   - name: wiki_js
#     version: 0.1.0
#     repository: https://charts.js.wiki
#     namespace: wiki

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-deployment
  namespace: wiki
spec:
  replicas: 1
  project: default
  source:
    chart: wiki
    repoURL: https://charts.js.wiki
    targetRevision: 0.1.0
    helm:
      releaseName: wiki
  destination:
    server: "https://kubernetes.default.svc"
    namespace: wiki