# dependencies: 
#   - name: wiki_js
#     version: 0.1.0
#     repository: https://charts.js.wiki
#     namespace: wiki

apiVersion: apps/v1
kind: Application
metadata:
  name: wiki-deployment
  namespace: wiki
spec:
  project: default
  # selector:
  #   matchLabels:
  #     app: wiki
  # template:
  #   metadata:
  #     labels:
  #       app: wiki
  source:
    repoURL: https://charts.js.wiki/requarks
    chart: wiki
    targetRevision: 0.1.0
    helm:
      releaseName: wiki.js
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: wiki