apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin4
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.runix.net
    chart: pgadmin4
    # targetRevision: 25.3.1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true