apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiki
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  replicas: 2
  source:
    repoURL: https://charts.js.wiki
    # chart: requarks/wiki
    chart: wiki
    targetRevision: 2.2.20
    helm:
      releaseName: wiki
      # valueFiles:
      #   - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true